### ISSUE TITLE
This doesn't work in node, but readme says it should.

### ISSUE THREAD

**Issue by JamesKyburz** [kahnvex/cookie-monster#19]
Nothing is exported in node.js as document is undefined.

if (typeof document !== 'undefined') module.exports = exports = bake(document);

**Comment by 3rd-Eden** [comment]
Due to lack of response on this ticket, I have forked and cleaned it up as [`koekiemonster`](https://github.com/unshiftio/koekiemonster)

**Comment by kahnvex** [comment]
This is an open source project. Pull requests are welcome as you can see [here](https://github.com/kahnjw/cookie-monster/pulls?q=is%3Apr+is%3Aclosed).
